Developer
Bedu2/CH2Green pull request #6
Opened 2018-10-11 16:28 UTC by MGMike0

Final bien mamalon

2018-10-11 16:50 UTC, RodolfoSaldivar requested changes

2018-10-11 16:50 UTC, RodolfoSaldivar commented on src/actions/DependientesActions.js
> +export const TraerDependientes = (id) => async(dispatch) =>{
los métodos tienen que empezar con minúscula

2018-10-11 16:50 UTC, RodolfoSaldivar commented on src/actions/UsuariosActions.js
> +export const Direccion = (id) => async(dispatch) =>{
los métodos tienen que empezar con minúscula, cámbialo en todos

2018-10-11 16:50 UTC, RodolfoSaldivar commented on src/components/Dependientes/AgregarDependiente.js
> +			props.EnviarDependiente(valores, props.dependientes)
al cambiar los métodos a minúscula, estos también cambian

2018-10-14 04:15 UTC, MGMike0 commented
Pues ya es todo, de los cambios que pediste solamente cambie los colores y puse el container a todo para tener una mejor pantalla pero no cambie los nombres

2020-11-19 14:28 UTC, closed without merging